namespace SharpEnd.Neckson
{
    enum ITEMVARIATIONOPTION
    {
        ITEMVARIATION_NONE = 0x0,
        ITEMVARIATION_BETTER = 0x1,
        ITEMVARIATION_NORMAL = 0x2,
        ITEMVARIATION_GREAT = 0x3,
        ITEMVARIATION_PERPECT = 0x4,
        ITEMVARIATION_MAKING_BEGIN = 0x5,
        ITEMVARIATION_MAKING_1 = 0x5,
        ITEMVARIATION_MAKING_2 = 0x6,
        ITEMVARIATION_MAKING_3 = 0x7,
        ITEMVARIATION_MAKING_4 = 0x8,
        ITEMVARIATION_MAKING_5 = 0x9,
        ITEMVARIATION_MAKING_6 = 0xA,
        ITEMVARIATION_MAKING_7 = 0xB,
        ITEMVARIATION_MAKING_8 = 0xC,
        ITEMVARIATION_MAKING_9 = 0xD,
        ITEMVARIATION_MAKING_10 = 0xE,
        ITEMVARIATION_MAKING_MASTER = 0xF,
        ITEMVARIATION_MAKING_MEISTER = 0x10,
        ITEMVARIATION_MAKING_END = 0x10,
        ITEMVARIATION_COUNT = 0x11,
    };
}
